### ISSUE TITLE
[request] thaumic addition support

### ISSUE THREAD

**Issue by Biviho** [Project-RT/RandomTweaker#58]
hi, sorry to bother you, you are one of the few that is still adding compatibility to crafttweaker, so i wanted to ask if you would like to add some compatibility with thaumic addition to customize some of the feature that does not have any way to be changed:

-Flux concentrator: a way to add recipe for block conversion. this should be possible looking at the code 

-vis salt: a way to add/change potion effects to vis salt. basically, every mod that add essentia is not handled by thaumic addition, so those are basically usless. this i don't know if it's possible to do

let me know if you like this ideas and the possibility of implementing at least the first

**Comment by Biviho** [comment]
yeah, i know how it is ahah, take your time, and i will do all the help i can, i'm not a native english speaker either, but i have no problem in understanding it :)
About the mod, the right one is: Thaumic Addition Reconstucted, wich is the one for the latest version of thaumcraft (it's also the only one there is for what i know)

-----------------------------------Flux Concentrator
some more description: 
the flux concentrator is a machine that transform blocks in an area around itself in other blocks
by default it transform shrooms into visshrooms and pumpkin into a flux version of pumpkins.
looking in the code there is an example on how the recipe is applied in  ThaumicAddition/src/main/ java/com/zeitheron/thaumicadditions/init/RecipeTAR.java at line 75

also for what i can see there is no easy way to remove an already registered recipe, since the map where recipes are stored is private (i've never made a mod, so i don't know if there is some trick to do that)

----------examples:
for the flux concentrator an example should be something like:
concentrator.Add( <modname:inputBlock>, <modname:outputBlock> );

so, for example:

```
import mods.randomtweaker.thaumaddition.concentrator;
concentrator.Add(<minecraft:wool>,<minecraft:stone>);
```

if it's possible to remove an already registered recipe, something like this would be ok:
concentrator.Remove(<modname:inputBlock>);
since one input correspond to one output

```
import mods.randomtweaker.thaumaddition.concentrator;
concentrator.Remove(<minecraft:pumpkin>);
```


--------------------------------vis salt
vis salt is a mechanic in thaumic additon that give you the ability to create crushed vis crystal that, when eaten, applied on the cake or dispersed/fired with the gun, will apply an effect on the eater/target.
an exapmple on how it is applied can be found in ThaumicAddition/src/main/ java/com/zeitheron/thaumicadditions/api/EdibleAspect.java at line 45.
those are registered statically in the class, but the function addEatCall is public and also the two maps where the effect is registered are public public, so it might be possible to remove already registered recipes.

vis salt are used by 4 different items:
-salt essence, the vis salt, wich contains the essence used in arcane cake and aura disperser to set the effect
-aura cake that can recive effects from vis salts
-arcane dispenser that apply effects to entity based on the salt inside it
-arcane pistol wich shoot essentia effect form liquid essentia

it should be also applicable to foods, but i didn't tested it

-----------examples
by looking at the code ti uses a function to register the effect that take the entity and a "count" wich i tiìhink is the amount of salt used, configurable in some machines.
i don't know if it's possible to apply a crafttweaker function to the use of a vis salt, but a potion effect should be enough, since the majority of those are actually potion effects.
looking at the code there is a lot to handle:
   - thaumc addition uses a formula to decide time and strenght of the potion effect so there is the need to handle that
   - there is the need to know the aspect but i don't know if there is an easy way to get that by for example a string, or if thaumcraft or modtweaker give the ability to return an aspect with crafttweaker...

to handle the formula it could be done with an input string to imitate the formula he already uses, something like:
 "fixed" for an integer
"quadratic" for an integer that will be summed to count*count
"sqrt" for an integer summed to sqrt(count)
"proportional" for an integer that will be placed in a formula: count*int/MAX_ESSENTIA (file EdibleAspect.java line 58)

an example could be: (i don't know how aspect could be defined)
ediblesalt.AddPotion(ASPECT, <potion:modname:potionname>, "string formula type", int time, "string formula type", int amplifier);

so something like: (example based on the already defined aspect ENERGY on EdibleAspect.java line 51)
(i don't know how aspect would be defined)

```
import mods.randomtweaker.thaumaddition.ediblesalt;
ediblesalt.AddPotion(ENERGY,<potion:minecraft:strength>, "quadratic", 20, "sqrt", 0);

```

if it's possible to remove them, then something like

ediblesalt.Remove(ASPECT)



there are also other things in thaumic addition that could be enhanced, for example the Shadow Enchantment, if you are interested in also adding that, you can find an example on how enchantment are registered in ThaumicAddition/src/main/java/com/zeitheron/thaumicadditions/TAReconstructed.java on line 188

also, there are the seal effects, wich are effects applied in an area based on seal combinations...but for how it's implemented i'm afraid it can't be customized...
you can find the recipe registration at:
ThaumicAddition/src/main/java/com/zeitheron/thaumicadditions/init/SealsTAR.java line 29


i hope i've been of some help, let me know if you need something!

**Comment by ikexing-cn** [comment]
thank you for your help, but I need some time to deal with the reality of things, so it will drag on some, and I'll try to make sure this content comes to fruition within this month. :(

**Comment by Biviho** [comment]
Yeah! Don't worry, no need to rush things! c:

**Comment by ikexing-cn** [comment]
hmm, I need some help. 
for the flux concentrator I don't understand how to use it. and I try to spawn a flux rift, but the block don't work.
By the way, 
I try to remove and add recipes is working for Jei,  add recipe is okay, but remove don't show,  just I don't know it's really working.

**Comment by Biviho** [comment]
there is no need to spawn a flux rift, the concentrator work with vitium essentia

the flux concentrator work by creating an enclosed chamber with the concentrator facing the inside and feeding it with vitium essentia, you will notice that the valve will start to spin and air block inside the camber will spawn taint parcticles.
if mushrooms are placed inside , thei will transform into visshroom after a bit and creature inside should get the flux flue potion effect

the flux concentrator might be a bit bugged cause for what i tested pumpkin will not transform

by the way, here is a setup for the concentrator

![2022-02-24_13 27 46](https://user-images.githubusercontent.com/57569917/155524060-d6e04187-80d5-4bc2-9e3d-ab049a3ca4b8.png)



you can see it working when you notice the purple taint parcticles inside the chamber


![2022-02-24_13 29 01](https://user-images.githubusercontent.com/57569917/155524209-7e90fd8f-8b50-4086-9389-9f53e63ce790.png)


at this point, placing mushrooms inside will transform them into vishroom


![2022-02-24_13 32 01](https://user-images.githubusercontent.com/57569917/155526946-55c39928-a3ed-46b5-94fb-c652acf97f1f.png)



i have noticed that each concentrator will tranform blocks only in an area 3x3x2 in front of them, that's why i placed more around the chamber


![2022-02-24_13 47 45](https://user-images.githubusercontent.com/57569917/155527163-1e22bcf0-540a-4101-969c-d76d517bfaa0.png)

**Comment by Biviho** [comment]
hi, it looks like Thaumic Addition: Reconstructed got an update that fixed pumpkins conversion, you might want to take a look into that
[the new version](https://www.curseforge.com/minecraft/mc-mods/thaumic-additions/files/3663195)

**Comment by ikexing-cn** [comment]
hi, i'm back and I will test further thanks.

**Comment by ikexing-cn** [comment]
hi, I think I'm done for concentrator support, in my test everything is okay but I can't guarantee any omission.
so if you have free time，I hope you can test for me, thanks!

the crafttweaker support on [this](https://github.com/Project-RT/RandomTweaker/blob/1.12.2-New/src/main/java/ink/ikx/rt/api/mods/thaumicadditions/IFluxConcentrator.java)

[click download](https://github.com/Project-RT/RandomTweaker/files/8148609/RandomTweaker-1.2.10.zip)

**Comment by Biviho** [comment]
oh, cool, will test it in a couple hour!

**Comment by Biviho** [comment]
tested it a bit, it looks like yup, addRecipes work while removeRecipes does not, but i personally think it's ok, thematically the default recipes are ok, so i guess they can stay.
thank you so much!

**Comment by ikexing-cn** [comment]
can you give me your srcipt for me look? in my test removeRecipe was okay..


and removeRecipe should remove for output not input...



---Original---
From: ***@***.***&gt;
Date: Sun, Feb 27, 2022 21:32 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Project-RT/RandomTweaker] [request] thaumic addition support (Issue #58)




 
tested it a bit, it looks like yup, addRecipes work while removeRecipes does not, but i personally think it's ok, thematically the default recipes are ok, so i guess they can stay.
 thank you so much!

**Comment by Biviho** [comment]
oh, i might have misread in the api, i used removeRecipes by input, not output, i will do a new test to see if it works and edit this message

**Comment by ikexing-cn** [comment]
okay, it's&nbsp;my bad, I moidify method but missing other method.

**Comment by ikexing-cn** [comment]
because there is more than one block state except vishroom, I don't know how to ensure that all states are deleted correctly.
so……maybe you should using `IFluxConcentrator.removeRecipes(IBlockstate output)` to remove all state, but it's so complicated.
maybe I can control `IFluxConcentrator.removeRecipes(IItemStack output)` to remove all state for block?
It depends on what you think.

**Comment by Biviho** [comment]
well, i guess that if a packev want to remove a recipe, it want to remove all the recipe about a specific item, so if it's possible to remove all the possible states it would be good

**Comment by ikexing-cn** [comment]
I think maybe I done the needs.
in my test everything is okay again, but I still need your help with testing to make sure I don't make some low-level mistakes.

the crafttweaker support on [this](https://github.com/Project-RT/RandomTweaker/blob/1.12.2-New/src/main/java/ink/ikx/rt/api/mods/thaumicadditions/IFluxConcentrator.java)

[click download](https://github.com/Project-RT/RandomTweaker/files/8154013/RandomTweaker-1.2.10.zip)

**Comment by Biviho** [comment]
just tested and it's working all fine!

**Comment by ikexing-cn** [comment]
关于vis salt，我目前的想法是这样的。
```zenscript

// CTAspect is the responsibility of modtwoaker. I don't want to do create a new again.

IEdibleAspect.addEatCall(CTAspect, (count) -> {
return IPotionEffect;
});
IEdibleAspect.addEatCall(CTAspect, (player, count) { 
// do something
return true | false;
});

```
what do you think about this?

**Comment by Biviho** [comment]
you mean for the crafttweaker method or the actual java implementation?

cause for the crafttweaker method i don't think you need to add the player and for the java implementation should be possible to just call the function provided by thaumicAddition, right?

(i might be wrong / misinterpreting your question / not skilled enough in java and functional programming to understand what you mean)

**Comment by ikexing-cn** [comment]
I mean for the crafttweaker method.
maybe the following example will be a little more intuitive to understand.

```zenscript
IEdibleAspect.addEatCall(<aspect:ignis>.internal, function(count) {
    return <potion:minecraft:strength>.makePotionEffect(10 * count, count * count);
});

IEdibleAspect.addEatCall(<aspect:ignis>.internal, function(entityLiving, count) {
    if (entityLiving instanceof IPlayer) {
        player.currentItem.mutable().shrink();
        <potion:minecraft:strength>.makePotionEffect(10 * count, count * count);
        return true;
    }
    return false;
});
```
> to handle the formula it could be done with an input string to imitate the formula he already uses, something like:
"fixed" for an integer
"quadratic" for an integer that will be summed to count * count
"sqrt" for an integer summed to sqrt(count)
"proportional" for an integer that will be placed in a formula: count*int/MAX_ESSENTIA (file EdibleAspect.java line 58)

I find it difficult to express more really content by relying on these fixed formulas.
so I want packev to design its own content.

**Comment by ikexing-cn** [comment]
okay, I've finished the vis salt support, the above plus `IEdibleAspect.removeEatCall(CTAspect aspect)` is all there is to it
About the following two, I'm afraid I can not give the corresponding support, so I can only stop, thanks for the help, another rt latest version because an pull request did not merge, so temporarily will not be released.
the issue will not be closed until I have released a new version.
but I can't guarantee that there are no mistask, so if you have time you can help to test it again.

oh, about the import, using `mods.randomtweaker.thaumadditions.IEdibleAspect`

well, that should be it.

[click download](https://github.com/Project-RT/RandomTweaker/files/8161217/RandomTweaker-1.2.10.zip)

**Comment by Biviho** [comment]
oh yeah! i see it now! a way better implementation than my proposal (i was going for the simplest, dumbest one to implement, your is pretty refined), will test it now

**Comment by Biviho** [comment]
first thing i noticed: loading a world without doing anything ( i haven't added a script yet ) it says: Error:system:EatFunction is already defined in that package, is this intended?

**Comment by ikexing-cn** [comment]
some low-level mistake, I'm so fucking overconfident not to do really test...
it will be fixed at night .

**Comment by ikexing-cn** [comment]
hi, the aspect is now IAspect, which no longer depends on modtweaker, but provides compatibility with it. If you use a CTAspect instance you can use as IAspect to convert to RT's aspect. also, you can use `IAspect.of(name as string)` to get an instance object of IAspect, or null if not found. and new is the `IAspect.getAllAspects()` method, the details of which are in [IAspect](https://github.com/Project-RT/RandomTweaker/blob/1.12.2-New/src/main/java/ink/ikx/rt/api/mods/thaumcraft/IAspect.java).

on the other hand, I found that I would lose the number of instances if I didn't return an AspectList instance, so I built an intermediate class of IAspectList support is also provided for modtweaker, and specific information is available from [ExpandIAspectList](https://github.com/Project-RT/RandomTweaker/blob/1.12.2-New/src/main/java/ink/ikx/rt/api/mods/thaumcraft/expand/ExpandIAspectList.java) and [IAspectList](https://github.com/Project-RT/RandomTweaker/blob/1.12.2-New/src/main/java/ink/ikx/rt/api/mods/thaumcraft/IAspectList.java) to get them.

the api specifically about IEdibleAspect hasn't changed much, but I added `applyToFoodStack` and `getSalt` methods, the details can be found in [IEdibleAspect](https://github.com/Project-RT/RandomTweaker/blob/1.12.2-New/src/main/java/ink/ikx/rt/api/mods/thaumicadditions/IEdibleAspect.java) to get them.

If you have any problems, please give me feedback and I will go fix it as soon as possible.

[RandomTweaker-1.2.10.zip](https://github.com/Project-RT/RandomTweaker/files/8176643/RandomTweaker-1.2.10.zip)

**Comment by Biviho** [comment]
Hi! Great! Will check it later today (around 3-4 h) and let you know

**Comment by Biviho** [comment]
EatFunction still require me to give 2 inputs, is this intended?
even adding 2 inputs i'm still getting an error wich i don't understand:

```
[INITIALIZATION][CLIENT][ERROR] [crafttweaker]: Error executing {[0:crafttweaker]: ThaumicAddition.zs}: JVMVRFY012 forma stack non coerente; classe=CrafttweakerThaumicAddition4, metodo=apply(Lcrafttweaker/api/entity/IEntityLivingBase;I)Z, pc=17
Exception Details:
  Location:
    CrafttweakerThaumicAddition4.apply(Lcrafttweaker/api/entity/IEntityLivingBase;I)Z @17: JBireturn
  Reason:
    Expected return type 'V' in the function.
  Stackmap Table:
java.lang.VerifyError: JVMVRFY012 forma stack non coerente; classe=CrafttweakerThaumicAddition4, metodo=apply(Lcrafttweaker/api/entity/IEntityLivingBase;I)Z, pc=17
Exception Details:
  Location:
    CrafttweakerThaumicAddition4.apply(Lcrafttweaker/api/entity/IEntityLivingBase;I)Z @17: JBireturn
  Reason:
    Expected return type 'V' in the function.
  Stackmap Table:
	at ThaumicAddition.__script__(ThaumicAddition.zs:17)
	at __ZenMain__.run(ThaumicAddition)
	at crafttweaker.runtime.CrTTweaker.loadScript(CrTTweaker.java:240)
	at crafttweaker.runtime.CrTTweaker.loadScript(CrTTweaker.java:105)
	at youyihj.zenutils.impl.delegate.ZenUtilsTweaker.loadScript(ZenUtilsTweaker.java:47)
	at crafttweaker.mc1120.events.CommonEventHandler.registerRecipes(CommonEventHandler.java:71)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2074_CommonEventHandler_registerRecipes_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:857)
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:636)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:747)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:3931)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


```

this is the script i'm using, am i doing something wrong? could you give me an exampe of a script that can work to see how it should be wrote?


```
IEdibleAspect.addEatCall(IAspect.of("potentia"), 
function(entity,count) as EatFunction
{
    return <potion:potioncraft:lightning>.makePotionEffect(10 * count, count * count);
}
);
```

**Comment by ikexing-cn** [comment]
EatFunction just one parameter.
u dont should get entity for it.

if u need using entity parameter, you should using EatFunctionWithEntity.

 example:
```zs
IEdibleAspect.addEatCall(IAspect.of("potentia"), 
function(count) as EatFunction
{
    return <potion:potioncraft:lightning>.makePotionEffect(10 * count, count * count);
}
);

IEdibleAspect.addEatCall(IAspect.of("potentia"), 
function(entity,count) as EatFunctionWithEntity
{
    return <potion:potioncraft:lightning>.makePotionEffect(10 * count, count * count);
}
);

**Comment by Biviho** [comment]
tested both functions: the first one told me that 2 inputs are expected
the second one gave me the same error as before

**Comment by ikexing-cn** [comment]
okay, `zenscript` for functional programming is not consistent with java, resulting in the same method parameters, they do not handle internal methods in a form parameter very well, so I modified the class to change the name of the method containing `entity` to `addAdvancedEatCall`, which ensures that ` zenscript` can handle parameters better.

Example:
```zs
IEdibleAspect.removeEatCall(IAspect.of("aqua"));
IEdibleAspect.removeEatCall(IAspect.of("ignis"));

IEdibleAspect.addEatCall(IAspect.of("ignis"), function(count) {
    return <potion:minecraft:strength>.makePotionEffect(10 * count, count * count);
});

IEdibleAspect.addEatCall(IAspect.of("ignis"), function(entity, count) {
    if (entity instanceof IPlayer) {
         var player as IPlayer = entityLiving;
        player.currentItem.mutable().shrink();
        <potion:minecraft:strength>.makePotionEffect(10 * count, count * count);
        return true;
    }
    return false;
});
```

some tips, if you need to override an instance of IEdibleAspect, make sure your remove code is on top of the add code in your script.

**Comment by Biviho** [comment]
ok, i've tested a bit and it looks like it's working correctly now! no more errors and i was able to apply potions with all the methods provided by thaumic addition (aura dispenser, pistol, eating food with essentia)

ive had the time to test only the EatFunction, but i will test more advanced uses in the future and let you know if i find something odd

**Comment by ikexing-cn** [comment]
hi, the new version has been released on https://www.curseforge.com/minecraft/mc-mods/randomtweaker/files/3677505
thanks for the recent help
