### ISSUE TITLE
[特性建议]自定义mekanism灌注类型

### ISSUE THREAD

**Issue by Ironnoob73** [Project-RT/RandomTweaker#60]
mekanism的冶金灌注机可以将红石、钻石等转换为浆液灌注进另一样物品进行制作，但是crtwiki称无法自定义新的灌注类型。故可否添加对自定义灌注类型的支持？

**Comment by ikexing-cn** [comment]
请使用[mekatweaker](https://www.mcmod.cn/class/6078.html)

具体的使用实例在我的整合包`AutoTech`中有。
[script](https://github.com/Project-AT/AutoTech/blob/main/.minecraft/scripts/Mekatweaker/infuser.zs)
[resources](https://github.com/Project-AT/AutoTech/tree/main/.minecraft/resources/mekatweaker)
