### ISSUE TITLE
crash on startup with the latest version

### ISSUE THREAD

**Issue by Biviho** [Project-RT/RandomTweaker#63]
hi! i'm getting this crash after updating to the latest version

https://pastebin.com/BiFaeayE

**Comment by ikexing-cn** [comment]
hi, can you may try updating `zenutils` and `crafttweaker`, I noticed they are a few versions behind.

**Comment by Biviho** [comment]
oh! sorry! i went to my pack after a while and didn't noticed the update, will do as soon as i can and let you know!

**Comment by Biviho** [comment]
i updated those mods, but the issue remains...
the crash happens only with some mods (for example with dimensional doors, industrial wires, greenery), so it might be a problem caused by an other lib mode, it will take a while to find the issue, i will let you know

**Comment by Biviho** [comment]
Ok...that's odd:
I've tried messing around with the mods in the pack, but it looks like none of them is causing this interaction :/

However, those mods above that i was testing in the pack, all caused some crash at some point, but not aleays at startup o_O

So i would say that, untill i can definitely prove the interaction, random tweaker it's not directly involved in the crash

**Comment by Biviho** [comment]
after a bit of testing, i'm pretty sure that the crash happen only when there is a mod that lack some requirement.
for some reason it appear that randomtweaker crash before that mod can notify tha there is a requirment missing, disabling randomtweaker when there is a crash will notify about the missing mod, then reenabling randomtweaker after fixing the missing mod also fix the crash

pretty odd ahah

**Comment by ikexing-cn** [comment]
thanks for help, I'll find time to check it out
