### ISSUE TITLE
[特性建议]希望添加对修改匠魂宝典图标的支持

### ISSUE THREAD

**Issue by EdwinYoungSteve** [Project-RT/RandomTweaker#64]
如图，某些材料在源码中会将展示物品设置为“碎片”，希望能够增加更改此图标的语句。
![image](https://github.com/Project-RT/RandomTweaker/assets/99588600/d941ce54-d3a4-4617-8fc0-9910b979041b)
![image](https://github.com/Project-RT/RandomTweaker/assets/99588600/3500ff15-79e5-4c8f-9c77-633e317a3753)

**Comment by ikexing-cn** [comment]
此项目已没有精力进行新功能支持，仅限于BUG维护，当然，欢迎PR且会快速审查。
