### ISSUE TITLE
匠魂进化共鸣异常

### ISSUE THREAD

**Issue by xy177** [Project-RT/RandomTweaker#68]
在使用匠魂进化模组的共鸣后，匠魂工具的nbt会全部丢失，测试用包环境如图
https://imgse.com/i/piQRcJU]

已经测试过仅在存在RT后才会出现这一问题（且移除RT后不会出现这个问题）

**Comment by ikexing-cn** [comment]
提供下日志, /cc @Water-Moon

**Comment by xy177** [comment]
https://paste.fastmirror.net/?5baae3f16505922d#CD1pGCmH3k7KoesZKHonvYfiGRg58tPXP9qDxEVri3Jr
（如果日志指的是latest文件的话，如果我理解有误我会再传你所需要的）

**Comment by Searcher4** [comment]
https://github.com/Project-RT/RandomTweaker/blob/1.12.2-New/src/main/java/ink/ikx/rt/classTransforms/mods/astralsorcery/AttunementAltarMethodReflections.java#L41
如果删除这行代码，这个问题就会被解决，这个问题是因为，**在合成结果没有被事件更改时，被41行擦除了NBT的输入物品将会直接被输出**，此时如果有匠魂进化等模组用其他优先级较低的asm修改掉落物时，将会收到没有任何NBT的匠魂工具
删除这行代码后，有NBT但是没有参与被魔改后的祭坛配方的物品将会正常输出

**Comment by XHL315** [comment]
话说现在的版本还有这问题吗

**Comment by xy177** [comment]
> 现在发表的版本(1.4.5)还有这个问题吗

截止到目前版本，未在更新日志中看见任何相关修复次bug的说明(还未进行测试)，目前我这边有人看了眼，说原因是“虽然配方里记录了输入的nbt，但是完成共鸣后返回的时候忘了返回记录的nbt”

**Comment by xy177** [comment]
> 现在发表的版本(1.4.5)还有这个问题吗

目前纯净环境测试无问题，我再综合环境测试一下

**Comment by xy177** [comment]
1.5.4中已确认此bug修复

**Comment by XHL315** [comment]
忘记说明了，1.4.5 在 config 中添加了是否开启联动的选项，默认都是关闭的。
