### ISSUE TITLE
IBook.setMaterialPirority()使用情况出现异常

### ISSUE THREAD

**Issue by xy177** [Project-RT/RandomTweaker#70]
目前使用了RT的匠魂宝典材料排序功能，然后出现了以下情况:
测试包（只有RT匠魂等最基础的模组）匠魂宝典和盔甲锻造手册都成功被排序
实战环境里盔甲锻造手册被成功排序但是匠魂宝典完全没被排序

用于排序的zs文件https://paste.fastmirror.net/?7e7d09903be8baec#HLYxSyrTvtz8Y8YxbNHz9eYMegkxo4ARDt7dLAdUVDA6

crafttweaker输出文件https://paste.fastmirror.net/?c74a11e131c5ba91#99Wa46XsUatVv1ptMaVQtaYUZSvBna9NHiiQi5PLGZGc

latest文件https://paste.fastmirror.net/?2ca0e0e2c83b8f24#9gRhyisGWRSRGHBgcMegji46PbMJbM2xNChLEJauoXjk

![mmexport1699773506753](https://github.com/Project-RT/RandomTweaker/assets/67099921/a187a4d1-5401-4778-9ea7-1f5d9a0cbf54)
![mmexport1699773508331](https://github.com/Project-RT/RandomTweaker/assets/67099921/576fd2ec-fbf8-45c2-87d7-010180ff135f)

**Comment by ikexing-cn** [comment]
第三方模组的兼容性问题这边没办法处理，你得自行排查出是哪个拓展模组的情况

**Comment by xy177** [comment]
目前情况是我排序了全部材料，我主要是好奇为什么盔甲锻造手册被成功排序了但是匠魂宝典却失败了(还是说您的意思是第三方模组导致了它)

**Comment by ikexing-cn** [comment]
> 目前情况是我排序了全部材料，我主要是好奇为什么盔甲锻造手册被成功排序了但是匠魂宝典却失败了(还是说您的意思是第三方模组导致了它)

是的，与RT本体实现的功能无关，某个匠魂的拓展改变了匠魂书的某一页所以导致无法排序

**Comment by xy177** [comment]
好的，十分感谢您的解答，也抱歉占用您的时间了

**Comment by ikexing-cn** [comment]
如果你可以找到是哪个匠魂的拓展模组，可以**尝试**进行兼容

**Comment by xy177** [comment]
好，我会陆续尝试排除(可能的范围基本上在增加或改变了匠魂书某些页的模组对吧)
