### ISSUE TITLE
能否手动选择模组联动功能开启

### ISSUE THREAD

**Issue by cszxymzx** [Project-RT/RandomTweaker#72]
如题，部分联动例如匠魂星辉共鸣具有不稳定性
希望至少可以通过配置文件关闭联动从而解决部分兼容性问题

**Comment by ikexing-cn** [comment]
没有时间维护了捏，但是欢迎 PR。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月24日(周日) 凌晨0:57
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Project-RT/RandomTweaker] 能否手动选择模组联动功能开启 (Issue #72)




 
如题，部分联动例如匠魂星辉共鸣具有不稳定性
 希望至少可以通过配置文件关闭联动从而解决部分兼容性问题

**Comment by ikexing-cn** [comment]
Updated, [#61145d8](https://github.com/Project-RT/RandomTweaker/commit/61145d826bfe3534db8d22280972450d06a20f06)
