### ISSUE TITLE
希望增加可以直接增加IMutableStack中属性修饰符的方法

### ISSUE THREAD

**Issue by EdwinYoungSteve** [Project-RT/RandomTweaker#74]
希望增加可以直接增加IMutableStack中属性修饰符的方法。
简单来说，比如我要设计一个匠魂属性，内容是“该工具的主手攻击速度增加20%”。
想通过一个类似IItemStack.mutable().addNewModifiers(name as string, slot as string, number as float, addType as int, uuid as string);的方法直接即时修改一个物品的属性修饰符，每个uuid独立作用（可叠加）。

**Comment by EdwinYoungSteve** [comment]
slot是指作用槽位（就是原版的那个“在主手时/在胸甲时”这种），addType与“乘算”“加算”“百分比算”相关

**Comment by ikexing-cn** [comment]
欢迎 PR
