### ISSUE TITLE
(not actual issue) `FTBUltimine` Mixin trying to inject despite neither `FTBUltimine` mod installed or `AllowCrTControl` option enabled

### ISSUE THREAD

**Issue by Krutoy242** [Project-RT/RandomTweaker#78]
I don't have `FTBUltimine` installed, but according to `debug.log` file, RandomTweaker still trying to inject its code:

```java
[mixin]: @Mixin target com.feed_the_beast.mods.ftbultimine.client.FTBUltimineClient was not found mixins.randomtweaker.mods.json:ftbultimine.MixinFTBUltimineClient from mod unknown-owner
```

This is also sounds strange since its trying to inject even if this config option set to `false`:

```ruby
ftbultimine {
    # If true, Allow Crt to Control the FTBUltimine enable
    B:AllowCrTControl=false
}
```

I expect, for every tweak in `randomtweaker.cfg` file, if option is disabled, it should not inject code into other mods. I dont know how mixins works, but i suspect that this would make my modpack load tiny bit faster and reduce incompatibility with other mods that changing same classes.

**Comment by ikexing-cn** [comment]
I don't think this would take more than a few milliseconds even if it was actually injected, and about your question, yes we can, but there's not enough free time for update :(

**Comment by Robolightning** [comment]
I have the same issue. At versions upper 1.4.2 the game do not start

**Comment by ikexing-cn** [comment]
@Robolightning Are you sure same issue? It's just a meaningless log.

**Comment by Robolightning** [comment]
> @Robolightning Are you sure it's the same issue? It's just a meaningless log.

[debug.log](https://github.com/Project-RT/RandomTweaker/files/14808896/debug.log)
[latest.log](https://github.com/Project-RT/RandomTweaker/files/14808898/latest.log)
[launcher_log.txt](https://github.com/Project-RT/RandomTweaker/files/14808901/launcher_log.txt)
