### ISSUE TITLE
This function took about 2 seconds `ink.ikx.rt.impl.mods.crafttweaker.CraftTweakerExtension.registerAllClass()`

### ISSUE THREAD

**Issue by Krutoy242** [Project-RT/RandomTweaker#79]
Im profiled my `E2E-E` modpack and found that this function took 1.6 seconds to execute.

![image](https://github.com/Project-RT/RandomTweaker/assets/936618/32b585ea-2082-4e99-8129-695a82a44858)

## https://spark.lucko.me/1gJaCkUPrm?hl=301592

This is small in comparison to whole modpack, but since i have ~400 mods, i want to be sure each second spent by any mod is improving modpack and not an accidental bug😅
1.6 seconds is concerning for a single mod, when 200 of 400 mods loads in less than 0.1 second.

What does this function do? If it required for some mod feature, how can i disable this feature?

**Comment by ikexing-cn** [comment]
`CraftTweaker` compat, disabling it will not allow you to use any of mod features

**Comment by Krutoy242** [comment]
Strange. All other mods that have CraftTweaker compat doesn't require this amount of time to initialize. 
Does `RandomTweaker` using some kind of special mechanics to register compat?

**Comment by friendlyhj** [comment]
I'm curious how much time `crafttweaker.mc1120.CraftTweaker.onPreInitialization()` takes?

**Comment by Krutoy242** [comment]
> I'm curious how much time `crafttweaker.mc1120.CraftTweaker.onPreInitialization()` takes?

2.9 sec
![image](https://github.com/Project-RT/RandomTweaker/assets/936618/e717bed3-1fe9-4265-bde7-cb3000ceb8cf)

https://spark.lucko.me/1gJaCkUPrm?hl=3068

**Comment by friendlyhj** [comment]
So we move crt register stuff to zenutils. Then can you tell how much zenutils preinit cost?

**Comment by Krutoy242** [comment]
I will test it later. Write please what class and method should I search for?

**Comment by friendlyhj** [comment]
`youyihj.zenutils.ZenUtils.readSidedZenRegisters()`

**Comment by Krutoy242** [comment]
200ms 
https://spark.lucko.me/GU0xBk6eeB?hl=196627
![image](https://github.com/Project-RT/RandomTweaker/assets/936618/f192ae3a-5749-4b8e-9155-2716f0a9e7e2)

<sup>This is not relevant to the problem, just my curiosity - what was it? Did RandomTweaker use some unusual methods that other mods don't use? Did it do any unnecessary calculations during initialization?</sup>

**Comment by friendlyhj** [comment]
A zenclass should be registered when two mods are installed. For example, custom botania flowers should be enabled only contenttweaker and botania are installed. However, CraftTweaker API only allows to add a single mod dependency of zenclass. RandomTweaker has to add a special way to register these classes. Recently, ZenUtils added the same mechanism to implement it, so we migrated to zenutils.
2.9s -> 200ms, looks like RandomTweaker code is low performace.
