### ISSUE TITLE
Material item doesn't change the material in the material list

### ISSUE THREAD

**Issue by roidrole** [Project-RT/RandomTweaker#80]
I... suppose it's a bug.  In my script, I have the fillowing :
`mods.randomtweaker.tconstruct.IBook.changeMaterialItem(crystal_matrix, <extendedcrafting:material:24>);`
`mods.randomtweaker.tconstruct.IBook.changeMaterialItem(fluix_steel, <contenttweaker:fluix_steel>);`

When looking at the material list in tconstruct, I see the item being the shards, which is not the texture of these items. Screenshot : 
![image](https://github.com/Project-RT/RandomTweaker/assets/83431927/4c4bf9dd-5138-49c1-a5b8-bd5f897323ce)

But when I look at the item's page, I see this : 
![image](https://github.com/Project-RT/RandomTweaker/assets/83431927/9c5f6cee-f6b9-4378-a806-01ecfa79f5fc)
Which has the right item associated to the material

As such, I am confident my script is right and this is an error in the mod

**Comment by ikexing-cn** [comment]
Can you provide all the TC expansion mods do you haven installed? I'm sure it works when just only TC.

**Comment by XHL315** [comment]
Are you enabling `iconModification`  in config?

**Comment by XHL315** [comment]
It will be fixed in 1.4.4. Waiting for a moment.

**Comment by XHL315** [comment]
Fix e33a62d
